// @ts-check
import { mkdirSync, writeFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import { legacyRedirects } from './src/utils/legacy-redirects';

const redirects = legacyRedirects();

/**
 * Emits the same redirect map as a real nginx 301 table (`deploy/nginx-redirects.conf`).
 *
 * Astro's static `redirects` build an HTML stub per legacy URL — Google follows
 * an instant meta refresh and passes ranking signals, so the stubs alone fix
 * the reported 404s on any static host. But the site runs on our own nginx, and
 * a `301` is unambiguous where a meta refresh is inferred, so nginx should win
 * the race (it answers before the stub is ever read). Generating the file here
 * rather than maintaining it by hand keeps the two in lockstep.
 */
function nginxRedirectTable() {
  return {
    name: 'nginx-redirect-table',
    hooks: {
      'astro:build:done': () => {
        const lines = Object.entries(redirects)
          .sort(([a], [b]) => a.localeCompare(b))
          .map(([from, to]) => `location = ${from} { return 301 ${to}; }`);

        mkdirSync(new URL('./deploy/', import.meta.url), { recursive: true });
        writeFileSync(
          new URL('./deploy/nginx-redirects.conf', import.meta.url),
          [
            '# GENERATED by astro.config.mjs (astro:build:done) — do not edit by hand.',
            '# Source of truth: src/utils/legacy-redirects.ts',
            '#',
            '# Legacy URLs Google still has indexed, 301d to their current equivalents.',
            '# Include from inside the `server` block of the site vhost:',
            '#   include /etc/nginx/snippets/handmadepastaflorence-redirects.conf;',
            '# Exact-match `location =` blocks take priority over prefix/regex matches,',
            '# so these resolve before the static-file handler returns its 404.',
            '',
            ...lines,
            '',
          ].join('\n'),
          'utf-8',
        );
      },
    },
  };
}

// https://astro.build
export default defineConfig({
  site: 'https://handmadepastaflorence.com',
  // Legacy URL shapes kept alive rather than left as 404s — see
  // src/utils/legacy-redirects.ts for what they are and where they came from.
  redirects,
  integrations: [nginxRedirectTable()],
  // Keep this list in sync with `languages` in src/i18n/config.ts.
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'it', 'fr', 'de', 'zh'],
    routing: {
      prefixDefaultLocale: false
    }
  },
  // Sitemap is hand-built at src/pages/sitemap-index.xml.ts + sitemap-0.xml.ts,
  // not @astrojs/sitemap: that integration's `i18n` option can only pair pages
  // whose URL pathname is identical across locales, so it silently emitted zero
  // hreflang alternates for every page with a per-locale translated slug (the
  // money pages + pasta-shapes hub/spokes — 50 of 85 URLs). The hand-built
  // version reuses the same data sources as each page's own <head> hreflang
  // tags, so the two can't drift apart. See src/utils/sitemap-entries.ts.
  build: {
    inlineStylesheets: 'always',
  },
  devToolbar: { enabled: false },
  vite: {
    build: {
      assetsInlineLimit: 0,
    },
  },
});
